config/routes.rb
FoobarStore::Application.routes.draw do
    
  resources :accounts

  resources :comments

  resources :related_products

  resources :categories

  resources :line_items

  resources :carts
  
  resources :sessions
  
  resources :products
  
  get "sessions/new"

  get "image/new"
  
  get "review/show"
  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "login" => "sessions#new", :as => "log_in"
  match "/register" => "Account#new", :as => "register"
  match "/carts/:id" => "Cart#show"
  match "/category/:id" => "Category#show"
  match "/admin" => "Admin#index"
  post "/login" => "Sessions#create"
  match "/accounts/new" => "Account#new"
  match "/images" => "Image#index"
  match "/highlights" => "Highlight#index"
  match "/csrftag" => "Application#csrf"

end

app/models/account.rb
class Account < ActiveRecord::Base

  attr_accessible :username, :password, :password_confirmation,:password_hash,:password_salt,:firstname,:lastname,:address,:is_admin
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :username
  validates_uniqueness_of :username
  validates :username, :uniqueness => true
  
  has_one :cart
  has_many :comments
  
  def self.authenticate(username, password)
    user = find_by_username(username)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
  def is_admin?
    if self.is_admin == 1
      return true
    else
      return false
    end
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, :dependent => :destroy
	belongs_to :account
	
	def add_product(product_id)
		current_item = line_items.find_by_product_id(product_id)
		if current_item
			current_item.quantity += 1
		else
			current_item = line_items.build(:product_id => product_id)
		end
		current_item
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	validates :name, :presence => true, :uniqueness => true
	
	has_many :products, :dependent => :destroy
	has_many :highlights, :dependent => :destroy
	
	before_destroy :ensure_not_referenced_by_any_product
	
	private
	
	def ensure_not_referenced_by_any_product
		if products.empty?
			return true
		else
			errors.add(:base, 'Products present')
			return false
		end
	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :user, :content, :product_id, :presence => true
  validates :product_id, :uniqueness => true
  
  belongs_to :product
  belongs_to :account
end

app/models/highlight.rb
class Highlight < ActiveRecord::Base
  belongs_to :category
end

app/models/image.rb
class Image < ActiveRecord::Base
  validates :url, :product_id, :presence => true
  validates :url, :format => {
    :with => %r{\.(gif|jpg|png)$}i,
    :message => 'Image URL must link to a GIF, JPG, PNG image.'
  }
  
  belongs_to :product
  belongs_to :related_product
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :product
	belongs_to :cart
end

app/models/product.rb
class Product < ActiveRecord::Base

	default_scope :order => 'title'

	validates :title, :description, :price, :category_id, :presence => true
	validates :category_id, :numericality => {:greater_than_or_equal_to => 1}
	validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
	validates :title, :uniqueness => true
	
	has_many :related_products, :dependent => :destroy
	has_many :line_items, :dependent => :destroy
	has_many :comments, :dependent => :destroy
	has_many :images, :dependent => :destroy
	has_one :highlight, :dependent => :destroy
	belongs_to :category
	
	before_destroy :ensure_not_referenced_by_any_line_item
	
	private
	
		def ensure_not_referenced_by_any_line_item
			if line_items.empty?
				return true
			else
				errors.add(:base, 'Line Items present')
				return false
			end
		end
		
end

app/models/related_product.rb
class RelatedProduct < ActiveRecord::Base
  validates :name, :product_id, :presence => true 
  
  belongs_to :product
  has_many :images
end

app/controllers/related_products_controller.rb
class RelatedProductsController < ApplicationController
  # GET /related_products
  # GET /related_products.json
  def index
    @related_products = RelatedProduct.all
    @specific_products = RelatedProduct.where(:product_id => params[:product_id])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @specific_products }
    end
  end

  # GET /related_products/1
  # GET /related_products/1.json
  def show
    @related_product = RelatedProduct.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @related_product }
    end
  end

  # GET /related_products/new
  # GET /related_products/new.json
  def new
    @related_product = RelatedProduct.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @related_product }
    end
  end

  # GET /related_products/1/edit
  def edit
    @related_product = RelatedProduct.find(params[:id])
  end

  # POST /related_products
  # POST /related_products.json
  def create
    @related_product = RelatedProduct.new(params[:related_product])
    
    respond_to do |format|
      if @related_product.save
        format.html { redirect_to '/products/'+@related_product.product_id.to_s, notice: 'Related product was successfully created.' }
        format.json { render json: @related_product, status: :created, location: @related_product }
      else
        format.html { render action: "new" }
        format.json { render json: @related_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /related_products/1
  # PUT /related_products/1.json
  def update
    @related_product = RelatedProduct.find(params[:id])

    respond_to do |format|
      if @related_product.update_attributes(params[:related_product])
        format.html { redirect_to @related_product, notice: 'Related product was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @related_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /related_products/1
  # DELETE /related_products/1.json
  def destroy
    @related_product = RelatedProduct.find(params[:id])
    @related_product.destroy

    respond_to do |format|
      format.html { redirect_to related_products_url }
      format.json { head :ok }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/highlight_helper.rb
module HighlightHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/related_products_helper.rb
module RelatedProductsHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/related_products/_form.html.erb
<%= form_for @related_product do |f| %>
  <% if @related_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@related_product.errors.count, "error") %> prohibited this related_product from being saved:</h2>

      <ul>
      <% @related_product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :product_id, :hidden => true %><br />
    <%= f.number_field :product_id, :value => params[:product_id], :readOnly => true, :hidden => true%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/related_products/edit.html.erb
<% content_for :admin do%>
<div id="lastViewContainer">
	<ul id="navlist">
		<li class="menu"><p> Admin </p></li>
		<li>
			<a href="/products">Manage Products</a>
		</li>
		<li>
			<a href="/related_products">Manage Related</a>
		</li>
		<li>
			<a href="/categories">Manage Categories</a>
		</li>
		<li>
			<a href="/accounts">Manage Accounts</a>
		</li>
	</ul>
</div>
<% end %>
<h1>Editing Related Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @related_product %> |
<%= link_to 'Back', related_products_path %>

app/views/related_products/index.html.erb
<% content_for :admin do%>
<div id="lastViewContainer">
	<ul id="navlist">
		<li class="menu"><p> Admin </p></li>
		<li>
			<a href="/products">Manage Products</a>
		</li>
		<li class="popupmenuprod">
			<a href="/related_products">Manage Related</a>
			<ul id="submenuprod">
				<li class="init"><%= link_to 'New Related', new_related_product_path %></li>
			</ul>
			</li>
		</li>
		<li>
			<a href="/categories">Manage Categories</a>
		</li>
		<li>
			<a href="/accounts">Manage Accounts</a>
		</li>
	</ul>
</div>
<% end %>
<h1>Listing Related Products</h1>

<table id="relProdList">
  <tr class="list_line_even">
    <th>Name</th>
    <th>Related to</th>
    <th>Management</th>
  </tr>

<% @related_products.each do |related_product| %>

 
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
  	
    <td class='list_description'><%= related_product.name %></td>
    <td class="related"><%= Product.find(related_product.product_id).title %></td>
    <td class="list_actions">
    	<%= link_to image_tag('/Images/icons/zoom.png'), related_product %>
   		<%= link_to image_tag('/Images/icons/pencil.png'), edit_related_product_path(related_product) %>
    	<%= link_to image_tag('/Images/icons/delete.png'), related_product, confirm: 'Are you sure?', method: :delete %>
    </td>
  </tr>
<% end %>
</table>

<br />

app/views/related_products/new.html.erb
<% content_for :admin do%>
<div id="lastViewContainer">
	<ul id="navlist">
		<li class="menu"><p> Admin </p></li>
		<li>
			<a href="/products">Manage Products</a>
		</li>
		<li>
			<a href="/related_products">Manage Related</a>
		</li>
		<li>
			<a href="/categories">Manage Categories</a>
		</li>
		<li>
			<a href="/accounts">Manage Accounts</a>
		</li>
	</ul>
</div>
<% end %>
<h1>New Related Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/related_products/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>
<% content_for :admin do%>
<div id="lastViewContainer">
	<ul id="navlist">
		<li class="menu"><p> Admin </p></li>
		<li>
			<a href="/products">Manage Products</a>
		</li>
		<li>
			<a href="/related_products">Manage Related</a>
		</li>
		<li>
			<a href="/categories">Manage Categories</a>
		</li>
		<li>
			<a href="/accounts">Manage Accounts</a>
		</li>
	</ul>
</div>
<% end %>
<p>
  <b>Name:</b>
  <%= @related_product.name %>
</p>

<p>
  <b>Image url:</b>
  <%= image_tag(@related_product.image_url) %>
</p>

<p>
  <b>Product:</b>
  <%= @related_product.product_id %>
</p>


<%= link_to image_tag('/Images/icons/pencil.png'), edit_related_product_path(related_product) %>
<%= link_to image_tag('/Images/icons/pencil.png'), related_products_path %>