config/routes.rb
FoobarStore::Application.routes.draw do
    
  resources :accounts

  resources :comments

  resources :related_products

  resources :categories

  resources :line_items

  resources :carts
  
  resources :sessions
  
  resources :products
  
  get "sessions/new"

  get "image/new"
  
  get "review/show"
  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "login" => "sessions#new", :as => "log_in"
  match "/register" => "Account#new", :as => "register"
  match "/carts/:id" => "Cart#show"
  match "/category/:id" => "Category#show"
  match "/admin" => "Admin#index"
  post "/login" => "Sessions#create"
  match "/accounts/new" => "Account#new"
  match "/images" => "Image#index"
  match "/highlights" => "Highlight#index"
  match "/csrftag" => "Application#csrf"

end

app/models/account.rb
class Account < ActiveRecord::Base

  attr_accessible :username, :password, :password_confirmation,:password_hash,:password_salt,:firstname,:lastname,:address,:is_admin
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :username
  validates_uniqueness_of :username
  validates :username, :uniqueness => true
  
  has_one :cart
  has_many :comments
  
  def self.authenticate(username, password)
    user = find_by_username(username)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
  def is_admin?
    if self.is_admin == 1
      return true
    else
      return false
    end
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, :dependent => :destroy
	belongs_to :account
	
	def add_product(product_id)
		current_item = line_items.find_by_product_id(product_id)
		if current_item
			current_item.quantity += 1
		else
			current_item = line_items.build(:product_id => product_id)
		end
		current_item
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	validates :name, :presence => true, :uniqueness => true
	
	has_many :products, :dependent => :destroy
	has_many :highlights, :dependent => :destroy
	
	before_destroy :ensure_not_referenced_by_any_product
	
	private
	
	def ensure_not_referenced_by_any_product
		if products.empty?
			return true
		else
			errors.add(:base, 'Products present')
			return false
		end
	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :user, :content, :product_id, :presence => true
  validates :product_id, :uniqueness => true
  
  belongs_to :product
  belongs_to :account
end

app/models/highlight.rb
class Highlight < ActiveRecord::Base
  belongs_to :category
end

app/models/image.rb
class Image < ActiveRecord::Base
  validates :url, :product_id, :presence => true
  validates :url, :format => {
    :with => %r{\.(gif|jpg|png)$}i,
    :message => 'Image URL must link to a GIF, JPG, PNG image.'
  }
  
  belongs_to :product
  belongs_to :related_product
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :product
	belongs_to :cart
end

app/models/product.rb
class Product < ActiveRecord::Base

	default_scope :order => 'title'

	validates :title, :description, :price, :category_id, :presence => true
	validates :category_id, :numericality => {:greater_than_or_equal_to => 1}
	validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
	validates :title, :uniqueness => true
	
	has_many :related_products, :dependent => :destroy
	has_many :line_items, :dependent => :destroy
	has_many :comments, :dependent => :destroy
	has_many :images, :dependent => :destroy
	has_one :highlight, :dependent => :destroy
	belongs_to :category
	
	before_destroy :ensure_not_referenced_by_any_line_item
	
	private
	
		def ensure_not_referenced_by_any_line_item
			if line_items.empty?
				return true
			else
				errors.add(:base, 'Line Items present')
				return false
			end
		end
		
end

app/models/related_product.rb
class RelatedProduct < ActiveRecord::Base
  validates :name, :product_id, :presence => true 
  
  belongs_to :product
  has_many :images
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
  		@cart = Cart.find(params[:id])        
  	rescue ActiveRecord::RecordNotFound  
  		logger.error "Attempt to access an invalid cart with id: #{params[:id]}"
  		redirect_to '/index', :notice => 'Invalid Cart'
  	else
	    respond_to do |format|
    	  format.html # show.html.erb
    	  format.json { render json: @cart }
      end
	  end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to carts_url }
      format.json { head :ok }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/highlight_helper.rb
module HighlightHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<% if !@current_user.nil? && @current_user.is_admin?%>
<h1>Listing carts</h1>

<table>
  <tr class="list_line_even">
    <th>Cart</th>
    <th>User</th>
    <th>Management</th>
  </tr>

<% @carts.each do |cart| %>
	<tr class="<%=cycle('list_line_odd','list_line_even')%>">
	  	<td><%= cart.id%></td>
	  	<td><%= Account.find(cart.user_id).username%></td>
	    <td>
	    	<%= link_to image_tag('/Images/icons/zoom.png'), cart %>
	   		<%= link_to image_tag('/Images/icons/pencil.png'), edit_cart_path(cart) %>
	   		<%= link_to image_tag('/Images/icons/delete.png'), cart, confirm: 'Are you sure?', method: :delete %>
	   	</td>
  	</tr>
<% end %>

</table>

<br />

<%= link_to 'New Cart', new_cart_path %>
<% else %>
<h1>Denied!</h1>
 <p>You don't have permission to view this page! Click <%= link_to 'here', '/index'%> to return to the index</p>
<% end %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% if !@current_user.nil?%>
<% if notice %>
	<p id="notice"><%= notice %></p>
<% end %>
<p>Continue Shopping? Click <%= link_to 'here', request.referer%></p>
<h3> Your Cart</h3>
<table class="cart">
	<tr>
		<th .class="order">Your Order</th>
		<th .class="unit">Unit Price</th>
		<th>Total Price</th>
	</tr>
<% total = 0 %>
<% @cart.line_items.each do |item|%>
	<tr>
		<td class="order">
			<%= item.quantity %> &times; <%= item.product.title %>
		</td>
		<td class="unit">
			<%= number_to_currency(item.product.price, :unit => "&euro;") %>
		</td>
		<td .class="subtotal">
			<%aux = item.quantity*item.product.price%>
			<%=number_to_currency(aux, :unit => "&euro;")%>
		</td>
	</tr>
	<% total += aux%>
<% end %>
	<tr>
		<td></td>
		<td class="total_label"><strong>Total:</strong></td>
		<td class="total"><%= number_to_currency(total, :unit => "&euro;")%></td>
	</tr>
</table>
<% else %>
 <h1>Denied!</h1>
 <p>Only registered users can shop! Click <%= link_to 'here', '/index'%></here>%=> to return to the index</p>
<% end %>