config/routes.rb
FoobarStore::Application.routes.draw do
    
  resources :accounts

  resources :comments

  resources :related_products

  resources :categories

  resources :line_items

  resources :carts
  
  resources :sessions
  
  resources :products
  
  get "sessions/new"

  get "image/new"
  
  get "review/show"
  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "login" => "sessions#new", :as => "log_in"
  match "/register" => "Account#new", :as => "register"
  match "/carts/:id" => "Cart#show"
  match "/category/:id" => "Category#show"
  match "/admin" => "Admin#index"
  post "/login" => "Sessions#create"
  match "/accounts/new" => "Account#new"
  match "/images" => "Image#index"
  match "/highlights" => "Highlight#index"
  match "/csrftag" => "Application#csrf"

end

app/models/account.rb
class Account < ActiveRecord::Base

  attr_accessible :username, :password, :password_confirmation,:password_hash,:password_salt,:firstname,:lastname,:address,:is_admin
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :username
  validates_uniqueness_of :username
  validates :username, :uniqueness => true
  
  has_one :cart
  has_many :comments
  
  def self.authenticate(username, password)
    user = find_by_username(username)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
  def is_admin?
    if self.is_admin == 1
      return true
    else
      return false
    end
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, :dependent => :destroy
	belongs_to :account
	
	def add_product(product_id)
		current_item = line_items.find_by_product_id(product_id)
		if current_item
			current_item.quantity += 1
		else
			current_item = line_items.build(:product_id => product_id)
		end
		current_item
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	validates :name, :presence => true, :uniqueness => true
	
	has_many :products, :dependent => :destroy
	has_many :highlights, :dependent => :destroy
	
	before_destroy :ensure_not_referenced_by_any_product
	
	private
	
	def ensure_not_referenced_by_any_product
		if products.empty?
			return true
		else
			errors.add(:base, 'Products present')
			return false
		end
	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :user, :content, :product_id, :presence => true
  validates :product_id, :uniqueness => true
  
  belongs_to :product
  belongs_to :account
end

app/models/highlight.rb
class Highlight < ActiveRecord::Base
  belongs_to :category
end

app/models/image.rb
class Image < ActiveRecord::Base
  validates :url, :product_id, :presence => true
  validates :url, :format => {
    :with => %r{\.(gif|jpg|png)$}i,
    :message => 'Image URL must link to a GIF, JPG, PNG image.'
  }
  
  belongs_to :product
  belongs_to :related_product
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :product
	belongs_to :cart
end

app/models/product.rb
class Product < ActiveRecord::Base

	default_scope :order => 'title'

	validates :title, :description, :price, :category_id, :presence => true
	validates :category_id, :numericality => {:greater_than_or_equal_to => 1}
	validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
	validates :title, :uniqueness => true
	
	has_many :related_products, :dependent => :destroy
	has_many :line_items, :dependent => :destroy
	has_many :comments, :dependent => :destroy
	has_many :images, :dependent => :destroy
	has_one :highlight, :dependent => :destroy
	belongs_to :category
	
	before_destroy :ensure_not_referenced_by_any_line_item
	
	private
	
		def ensure_not_referenced_by_any_line_item
			if line_items.empty?
				return true
			else
				errors.add(:base, 'Line Items present')
				return false
			end
		end
		
end

app/models/related_product.rb
class RelatedProduct < ActiveRecord::Base
  validates :name, :product_id, :presence => true 
  
  belongs_to :product
  has_many :images
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
	  @products = Product.find_all_by_category_id(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json:  @products.map {|p| [p.category_id, p.images, p, Category.find(p.category_id).highlights]}}
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :ok }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/highlight_helper.rb
module HighlightHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% content_for :admin do%>
<div id="lastViewContainer">
	<ul id="navlist">
		<li class="menu"><p> Admin </p></li>
		<li>
			<a href="/products">Manage Products</a>
		</li>
		<li>
			<a href="/related_products">Manage Related</a>
		</li>
		<li>
			<a href="/categories">Manage Categories</a>
		</li>
		<li>
			<a href="/accounts">Manage Accounts</a>
		</li>
	</ul>
</div>
<% end %>
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<% content_for :admin do%>
<div id="lastViewContainer">
	<ul id="navlist">
		<li class="menu"><p> Admin </p></li>
		<li>
			<a href="/products">Manage Products</a>
		</li>
		<li>
			<a href="/related_products">Manage Related</a>
		</li>
		<li class="popupmenuprod">
			<a href="/categories">Manage Categories</a>
			<ul id="submenuprod">
				<li class="init"><%= link_to 'New Category', new_category_path %></li>
			</ul>
		</li>
		<li>
			<a href="/accounts">Manage Accounts</a>
		</li>
	</ul>
</div>
<% end %>

<h1>Category Management</h1>

<table class="cat_list">
  <tr class="list_line_even">
    <th>Name</th>
    <th>Management</th>
  </tr>

<% @categories.each do |category| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    <td>
    	<%= category.name %>
    </td>
    <td class="list_actions">
    	<%= link_to image_tag('/Images/icons/zoom.png'), category %>
    	<%= link_to image_tag('/Images/icons/pencil.png'), edit_category_path(category) %> 
    	<%= link_to image_tag('/Images/icons/delete.png'), category, confirm: "Are you sure you want to delete #{category.name} from the store?", method: :delete %>
    </td>
  </tr>
<% end %>
</table>

app/views/categories/new.html.erb
<% content_for :admin do%>
<div id="lastViewContainer">
	<ul id="navlist">
		<li class="menu"><p> Admin </p></li>
		<li>
			<a href="/products">Manage Products</a>
		</li>
		<li>
			<a href="/related_products">Manage Related</a>
		</li>
		<li>
			<a href="/categories">Manage Categories</a>
		</li>
		<li>
			<a href="/accounts">Manage Accounts</a>
		</li>
	</ul>
</div>
<% end %>
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<% if notice %>
	<p id="notice"><%= notice %></p>
<% end %>
<% content_for :admin do%>
<div id="lastViewContainer">
	<ul id="navlist">
		<li class="menu"><p> Admin </p></li>
		<li>
			<a href="/products">Manage Products</a>
		</li>
		<li>
			<a href="/related_products">Manage Related</a>
		</li>
		<li class="popupmenuprod">
			<a href="/categories">Manage Categories</a>
			<ul id="submenuprod">
				<li class="init"><%= link_to 'Add Product to Category', '/products/new?category_id='+params[:id] %></li>
			</ul>
		</li>
		<li>
			<a href="/accounts">Manage Accounts</a>
		</li>
	</ul>
</div>
<% end %>

<h1>Listing Products in <%= Category.find(params[:id]).name%></h1>
<table id="prodList">
	<tr class="list_line_even">
		<th>Preview</th>
		<th>Product Details</th>
		<th>Price</th>
		<th>Management</th>
	</tr>
<% @products.each do |product| %>
	<tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
		<% if !Image.find_by_product_id(product.id).nil?%>
		<% image = Image.find_by_product_id(product.id).url%>
		<td><%= image_tag image, :class => "list_preview"%></td>
		<% else %>
			<td> Unexisting Preview</td>
		<% end %>
  		<td class='list_description'>
	    	<dl>
	    		<dt><%= product.title %></dt>
	    		<dd><%= truncate(strip_tags(product.description), :length => 80) %></dd>
	    	</dl>
		</td>
  		<td><%= number_to_currency(product.price, :unit => "&euro;") %></td>
  		<td class="list_actions">
  			<%= link_to image_tag('/Images/icons/zoom.png'), product %>
    		<%= link_to image_tag('/Images/icons/pencil.png'), edit_product_path(product) %> 
    		<%= link_to image_tag('/Images/icons/delete.png'), product, confirm: "Are you sure you want to delete #{product.title} from the store?", method: :delete %>
  		</td>
	</tr>
<% end %>
</table>

<%= link_to image_tag('/Images/icons/resultset_previous.png'), products_path %>